---
    - name: Apt Update
      apt: 
        update_cache: yes
    
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['software-properties-common','apt-transport-https', 'ca-certificates', 'curl', 'vim', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'docker-compose', 'python-pip', 'openjdk-11-jdk']
    
    
    ## https://stackoverflow.com/questions/51222996/docker-login-fails-on-a-server-with-no-x11-installed 
    # - name: Remove Golang-Docker-Credential Helpers because of existing bug
    #   apt:
    #     name: golang-docker-credential-helpers
    #     state: absent
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    - name: Install Docker Module for Python
      pip:
        name: docker, docker-compose
    
    - name: Start Service docker, if not started
      service:
        name: docker
        state: started
    
    - name: Check if destination already is there
      stat:
        path: /opt/hedera-mirror-node
      register: project_directory

    - name: Make sure our destinaton project directory isn't already there.
      file:
        path: /opt/hedera-mirror-node
        state: absent
      when: project_directory.stat.isdir is defined and project_directory.stat.isdir
    
    # Download Hedera Mirror Node Repository   
    - name: Download Hedera Mirror Node from Github
      git:
        repo: 'https://github.com/injectedfusion/hedera-mirror-node'
        dest: /opt/hedera-mirror-node
        clone: yes
        update: yes
    
    - name: Run Maven Clean Install, this will take a few minutes..
      shell: ./mvnw clean install -DskipTests
      args:
        chdir: /opt/hedera-mirror-node



