---
# tasks file for hedera-gcs-setup
- name: Install & Start Docker Engine
  include: install.yml
  become: true
  tags:
    - install

- name: Provide our credentials and Launch the Mirror Node
  include: run.yml
  become: true
  tags:
    - start_services

- name: Stop Services
  include: stop.yml
  become: true
  tags:
    - stop_services
