---
- name: Provide our Application Config
  template:
    src: templates/application.yml.j2
    dest: /opt/hedera-mirror-node/application.yml
    include_vars:
        dir: group_vars/
        extensions:
            - json