---

- name: Provide our Application Config
  template:
    src: templates/application.yml.j2
    dest: /opt/hedera-mirror-node/application.yml

- name: Uncomment line from docker-compose
  lineinfile:
    path: /opt/hedera-mirror-node/docker-compose.yml
    regexp: '\s#-\s..application.yml:\/usr\/etc\/hedera-mirror-importer\/application.yml'
    line: '      - ./application.yml:/usr/etc/hedera-mirror-grpc/application.yml'
    backrefs: yes

- name: Start Service docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Run `docker-compose up` and start Mirror Node Services
  docker_compose:
    project_src: /opt/hedera-mirror-node
    state: present